export const songs = [
  {
    spotifyId: "0VjIjW4GlUZAMYd2vXMi3b",
    title: "Blinding Lights",
    artist: "The Weeknd",
    mood: "hype",
    energy: 9,
    tags: ["pop", "synthpop", "energetic", "upbeat"],
  },
  {
    spotifyId: "4Dvkj6JhhA12EX05fT7y2e",
    title: "As It Was",
    artist: "Harry Styles",
    mood: "happy",
    energy: 7,
    tags: ["pop", "upbeat", "feel good"],
  },
  {
    spotifyId: "3JvKfv6T31zO0ini8iNItO",
    title: "Another Love",
    artist: "Tom Odell",
    mood: "sad",
    energy: 4,
    tags: ["sad", "emotional", "piano"],
  },
  {
    spotifyId: "7qiZfU4dY1lWllzX7mPBI3",
    title: "Shape of You",
    artist: "Ed Sheeran",
    mood: "happy",
    energy: 8,
    tags: ["pop", "dance", "upbeat"],
  },
  {
    spotifyId: "1mea3bSkSGXuIRvnydlB5b",
    title: "Viva La Vida",
    artist: "Coldplay",
    mood: "uplifting",
    energy: 7,
    tags: ["alternative", "anthemic", "uplifting"],
  },
  {
    spotifyId: "2takcwOaAZWiXQijPHIx7B",
    title: "Time",
    artist: "Pink Floyd",
    mood: "dark",
    energy: 5,
    tags: ["classic rock", "dark", "reflective"],
  },
  {
    spotifyId: "5uCax9HTNlzGybIStD3vDh",
    title: "Say You Won't Let Go",
    artist: "James Arthur",
    mood: "romantic",
    energy: 4,
    tags: ["love", "romantic", "acoustic"],
  },
  {
    spotifyId: "6habFhsOp2NvshLv26DqMb",
    title: "Despacito",
    artist: "Luis Fonsi",
    mood: "party",
    energy: 9,
    tags: ["latin", "dance", "party"],
  },
  {
    spotifyId: "2Fxmhks0bxGSBdJ92vM42m",
    title: "bad guy",
    artist: "Billie Eilish",
    mood: "dark",
    energy: 6,
    tags: ["dark pop", "alternative", "moody"],
  },
  {
    spotifyId: "5HCyWlXZPP0y6Gqq8TgA20",
    title: "Stressed Out",
    artist: "Twenty One Pilots",
    mood: "chill",
    energy: 6,
    tags: ["alternative", "chill", "reflective"],
  },
  {
    spotifyId: "2VxeLyX666F8uXCJ0dZF8B",
    title: "Shallow",
    artist: "Lady Gaga",
    mood: "emotional",
    energy: 5,
    tags: ["emotional", "ballad", "dramatic"],
  },
  {
    spotifyId: "3AJwUDP919kvQ9QcozQPxg",
    title: "Yellow",
    artist: "Coldplay",
    mood: "romantic",
    energy: 4,
    tags: ["romantic", "soft", "alternative"],
  },
];